
DROP FUNCTION IF EXISTS hello;
DELIMITER //
CREATE FUNCTION hello()
RETURNS CHAR(20) CHARSET UTF8
RETURN 'Hello Word';
//
DELIMITER ;


DROP FUNCTION IF EXISTS formatname;
DELIMITER //
CREATE FUNCTION formatname
(
  s1 VARCHAR(30) CHARSET UTF8,
  s2 VARCHAR(30) CHARSET UTF8
)
RETURNS VARCHAR(40) CHARSET UTF8
RETURN CONCAT ( s2, ' ', LEFT(s1, 2) );
//
DELIMITER ;

DELIMITER //
DROP FUNCTION IF EXISTS uppername //
CREATE FUNCTION formatname
(
  s1 VARCHAR(30)
)
RETURNS VARCHAR(30)
RETURN upper(s1);
//
DELIMITER ;
